[package]
name = "distributed"
version = "0.1.0"
authors = ["jcamposforner <jcamposforner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
serde_derive = "1.0.101"
lazy_static = "1.4.0"
